version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      # POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    # logging:
    #   options:
    #     max-size: 10m
    #     max-file: '3'
    expose:
      - 5438
    ports:
      - '5438:5432'
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
